version: 1.2
workflows:
   - subclass: wdl2
     primaryDescriptorPath: /Dockstore.wdl
     testParameterFiles:
     - /test.json
     authors:
     - name: GitHub App Test Author
   - subclass: wdl2
     name: workflow2
     primaryDescriptorPath: /Dockstore.wdl
     testParameterFiles:
     - /test.json
